// This file was generated by Prisma, and assumes you have already installed:
// npm install --save-dev prisma dotenv
import { config } from "dotenv";
import { defineConfig } from "prisma/config";

// env 统一在仓库根 .env（相对本包 cwd 解析）；包内 .env 兜底（容器/独立部署）
config({ path: ["../../.env", ".env"] });

/**
 * Prisma CLI 的数据库 URL 从 DB_* 组装，与运行时共用同一配置源；
 * 用户名/密码中的特殊字符按 URL 规则编码。不再使用独立的 DATABASE_URL，消除双源漂移。
 */
const databaseUrl = (): string => {
    const encode = (value: string): string => encodeURIComponent(value);
    const host = process.env.DB_HOST?.trim() || "localhost";
    const port = process.env.DB_PORT?.trim() || "3306";
    const user = process.env.DB_USERNAME?.trim() || "root";
    const password = process.env.DB_PASSWORD ?? "";
    const name = process.env.DB_DATABASE?.trim() || "zmdb";
    return `mysql://${encode(user)}:${encode(password)}@${host}:${port}/${name}`;
};

export default defineConfig({
    schema: "prisma/schema.prisma",
    migrations: {
        path: "prisma/migrations",
        seed: "tsx prisma/seed.ts",
    },
    datasource: {
        url: databaseUrl(),
    },
});
